### ISSUE TITLE
alcohol

### ISSUE THREAD

**Issue by GeertVerstraete** [kvanrobbroeck/recepten#1]
na 5 porties tiramisu kan ik nog altijd recht lopen, please add more alcohol!

**Comment by Tosirove** [comment]
na 5 flesjes alcohol kan ik nog altijd tiramisu eten, please bring more alcohol!

**Comment by penance007** [comment]
After bringing more alcohol, kan ik nog steeds 5 flesjes alcohol drinken en tiramisu eten!

**Comment by kvanrobbroeck** [comment]
Get out of here you trolls! And stop undermining my attempt to make the world a better place!
